name: Terraform checks
on: [push, pull_request]

jobs:
  terraform-linter:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init-bastion
        run: |
          cd modules/terraform-zsac-bastion-gcp
          terraform init   

      - name: Terraform Validate
        id: validate-bastion
        run: |
          cd modules/terraform-zsac-bastion-gcp
          terraform validate -no-color

      - name: Terraform Init
        id: init-zsac-acvm
        run: |
          cd modules/terraform-zsac-acvm-gcp
          terraform init   

      - name: Terraform Validate
        id: validate-zsac-acvm
        run: |
          cd modules/terraform-zsac-acvm-gcp
          terraform validate -no-color

      - name: Terraform Init
        id: init-zsac-network-gcp
        run: |
          cd modules/terraform-zsac-network-gcp
          terraform init   

          - name: Terraform Validate
          id: validate-zpa-app-connector-group
          run: |
            cd modules/terraform-zpa-app-connector-group
            terraform validate -no-color
  
      - name: Terraform Init
        id: init-zpa-app-connector-group
        run: |
          cd modules/terraform-zpa-app-connector-group
          terraform init   
          - name: Terraform Validate
          id: validate-zpa-provisioning-key
          run: |
            cd modules/terraform-zpa-provisioning-key
            terraform validate -no-color
  
      - name: Terraform Init
        id: init-zpa-provisioning-key
        run: |
          cd modules/terraform-zpa-provisioning-key
          terraform init   
    
